# Generated by Django 5.1.7 on 2026-02-18 11:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_document_options_and_more'), ('core', '0003_alter_document_doc_type'), ('core', '0004_rename_updated_at_document_uploaded_at'), ('core', '0005_document_quality_score'), ('core', '0006_document_user_edited_data'), ('core', '0007_rename_uploaded_at_document_updated_at_and_more'), ('core', '0008_document_is_edited_document_last_edited_at_and_more'), ('core', '0009_remove_document_is_edited_and_more'), ('core', '0010_alter_document_doc_type'), ('core', '0011_alter_document_doc_type'), ('core', '0012_alter_document_file'), ('core', '0013_remove_document_file'), ('core', '0014_document_file')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('user_edited_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[core.models.validate_file_size, core.models.validate_file_extension])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
