# Generated by Django 5.1.7 on 2026-08-23 12:33

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[core.models.validate_file_size, core.models.validate_file_extension])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('user_edited_data', models.JSONField(blank=True, default=dict)),
                ('ai_extracted_json', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
