# Generated by Django 5.1.7 on 2026-08-30 04:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('voter_id_card', 'Voter ID Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('vehicle_registration_certificate', 'Vehicle Registration Certificate'), ('domicile_certificate', 'Domicile Certificate'), ('nationality_certificate', 'Nationality Certificate'), ('birth_certificate', 'Birth Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('death_certificate', 'Death Certificate'), ('property_card', 'Property Card'), ('income_certificate', 'Income Certificate'), ('ration_card', 'Ration Card'), ('school_leaving_certificate', 'School Leaving Certificate'), ('ssc_marksheet', 'SSC Marksheet'), ('hsc_marksheet', 'HSC Marksheet'), ('degree_certificate', 'Degree Certificate'), ('board_passing_certificate', 'Board Passing Certificate'), ('caste_certificate', 'Caste Certificate'), ('caste_validity_certificate', 'Caste Validity Certificate'), ('non_creamy_layer_certificate', 'Non-Creamy Layer Certificate'), ('ews_certificate', 'EWS Certificate'), ('gst_certificate', 'GST Certificate'), ('invoice', 'Invoice'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[core.models.validate_file_size, core.models.validate_file_extension])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('user_edited_data', models.JSONField(blank=True, default=dict)),
                ('ai_extracted_json', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('offline_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_docume_user_id_e413de_idx'), models.Index(fields=['doc_type', 'processed'], name='core_docume_doc_typ_fdfb6c_idx'), models.Index(fields=['user', 'doc_type'], name='core_docume_user_id_e6c75a_idx'), models.Index(fields=['synced'], name='core_docume_synced_bada20_idx'), models.Index(fields=['user', 'created_at'], name='core_docume_user_id_71483f_idx')],
            },
        ),
    ]
