# Generated by Django 5.1.7 on 2026-08-25 07:14

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='offline_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='synced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('voter_id_card', 'Voter ID Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('vehicle_registration_certificate', 'Vehicle Registration Certificate'), ('domicile_certificate', 'Domicile Certificate'), ('nationality_certificate', 'Nationality Certificate'), ('birth_certificate', 'Birth Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('death_certificate', 'Death Certificate'), ('property_card', 'Property Card'), ('income_certificate', 'Income Certificate'), ('ration_card', 'Ration Card'), ('school_leaving_certificate', 'School Leaving Certificate'), ('ssc_marksheet', 'SSC Marksheet'), ('hsc_marksheet', 'HSC Marksheet'), ('degree_certificate', 'Degree Certificate'), ('board_passing_certificate', 'Board Passing Certificate'), ('caste_certificate', 'Caste Certificate'), ('caste_validity_certificate', 'Caste Validity Certificate'), ('non_creamy_layer_certificate', 'Non-Creamy Layer Certificate'), ('ews_certificate', 'EWS Certificate'), ('gst_certificate', 'GST Certificate'), ('invoice', 'Invoice'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[core.models.validate_file_size, core.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='core_docume_user_id_e413de_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'processed'], name='core_docume_doc_typ_fdfb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'doc_type'], name='core_docume_user_id_e6c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['synced'], name='core_docume_synced_bada20_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'created_at'], name='core_docume_user_id_71483f_idx'),
        ),
    ]
