# Generated by Django 5.1.7 on 2025-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('driving_license', 'Driving License'), ('voter_id_card', 'Voter ID Card'), ('vehicle_registration_certificate', 'Vehicle Registration Certificate'), ('domicile_certificate', 'Domicile Certificate'), ('bank_passbook', 'Bank Passbook'), ('birth_certificate', 'Birth Certificate'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('cast_validity_certificate', 'Cast Validity Certificate'), ('non_criminal_certificate', 'Non-Criminal Certificate'), ('marksheets_passing_certificates', '10th/12th Marksheet & Passing Certificate'), ('diploma_degree_certificate', 'Diploma / Degree / Provisional Certificate'), ('migration_certificate', 'Migration Certificate'), ('leaving_transfer_certificate', 'Leaving / Transfer Certificate'), ('bonafide_certificate', 'Bonafide Certificate'), ('passport', 'Passport'), ('ration_card', 'Ration Card'), ('aadhaar_enrollment_receipt', 'Aadhaar Enrollment Receipt'), ('bank_kyc_documents', 'Bank KYC Documents'), ('electricity_bill', 'Electricity Bill'), ('telephone_bill', 'Telephone Bill'), ('property_sale_deed', 'Property Sale Deed'), ('rent_agreement', 'Rent Agreement'), ('insurance_policy', 'Insurance Policy'), ('medical_records', 'Medical Records'), ('vehicle_insurance_certificate', 'Vehicle Insurance Certificate'), ('form16_salary_slip_it_returns', 'Form 16 / Salary Slip / IT Returns'), ('ews_minority_certificate', 'EWS / Minority Certificate'), ('trade_license_business_registration', 'Trade License / Business Registration'), ('employment_certificate', 'Employment Certificate'), ('police_clearance_character_certificate', 'Police Clearance / Character Certificate'), ('driving_test_certificate', 'Driving Test Certificate'), ('student_college_id', 'Student / College ID'), ('income_tax_acknowledgment_receipt', 'Income Tax Acknowledgment Receipt'), ('pension_social_security_documents', 'Pension / Social Security Documents'), ('loan_mortgage_documents', 'Loan / Mortgage Documents'), ('passport_application_receipt', 'Passport Application Receipt'), ('visa_oci_pio_documents', 'Visa / OCI / PIO Documents'), ('birth_death_marriage_divorce_certificate', 'Birth / Death / Marriage / Divorce Certificate'), ('adoption_guardianship_certificate', 'Adoption / Guardianship Certificate'), ('affidavit', 'Affidavit'), ('professional_government_license', 'Professional / Government License'), ('election_commission_acknowledgment', 'Election Commission Acknowledgment'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True),
        ),
    ]
