# Generated by Django 5.2.7 on 2025-10-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_document_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
    ]
