# Generated by Django 5.2.7 on 2025-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_updated_at_document_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
