# Generated by Django 5.1.7 on 2025-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_edited_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
