# Generated by Django 5.1.7 on 2025-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_user_edited_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True),
        ),
    ]
