# Generated by Django 5.1.7 on 2025-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_uploaded_at_document_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_data_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
