# Generated by Django 5.1.7 on 2025-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_document_is_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True),
        ),
    ]
