# Generated by Django 5.1.7 on 2025-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('other_document', 'Other Document')], default='other_document', max_length=50, null=True),
        ),
    ]
