# Generated by Django 5.1.7 on 2026-02-14 14:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.models.validate_file_size, core.models.validate_file_extension]),
        ),
    ]
