# Generated by Django 5.1.7 on 2026-02-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
