# Generated by Django 5.1.7 on 2026-02-15 14:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[core.models.validate_file_size, core.models.validate_file_extension]),
        ),
    ]
