# Generated by Django 5.1.7 on 2026-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0014_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_extracted_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
