# Generated by Django 5.1.7 on 2025-10-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
