"""
Django settings for ask_me project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

import os
from pathlib import Path
from decouple import config
from dotenv import load_dotenv
import pytesseract
from urllib.parse import urlparse, parse_qsl

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --------------------
# FILE UPLOAD LIMITS
# --------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# --------------------
# DATABASE
# --------------------
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": tmpPostgres.path.replace("/", ""),
        "USER": tmpPostgres.username,
        "PASSWORD": tmpPostgres.password,
        "HOST": tmpPostgres.hostname,
        "PORT": 5432,
        "OPTIONS": dict(parse_qsl(tmpPostgres.query)),
    }
}

# --------------------
# EMAIL
# --------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# --------------------
# SECURITY
# --------------------
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

CSRF_TRUSTED_ORIGINS = [
    "https://ask-me-smart-document-assistant.onrender.com",
]

# --------------------
# INSTALLED APPS
# --------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Local apps
    "account",
    "ask_me",
    "core.apps.CoreConfig",
]

# --------------------
# MIDDLEWARE
# --------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ask_me.urls"

# --------------------
# TEMPLATES
# --------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ask_me.wsgi.application"

# --------------------
# PASSWORD VALIDATION
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------
# GLOBAL SETTINGS
# --------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = config("TIME_ZONE", default="Asia/Kolkata")
USE_I18N = True
USE_TZ = True

# --------------------
# STATIC FILES
# --------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --------------------
# MEDIA FILES
# --------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# --------------------
# AUTH / SITE
# --------------------
SITE_ID = 1
LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "core:index"

# --------------------
# DEFAULT PK FIELD
# --------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------
# LOGGING
# --------------------
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "ask_me.log"),
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "ask_me": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# --------------------
# OCR SETTINGS (Safe for Render)
# --------------------
import shutil

PYTESSERACT_CMD = os.getenv("PYTESSERACT_CMD")

# A user-supplied PYTESSERACT_CMD can point at the *folder* Tesseract was
# installed into (e.g. "C:\Program Files\Tesseract-OCR") rather than the
# .exe itself. Trusting that blindly makes pytesseract try to execute a
# directory, which fails with a confusing PermissionError ([WinError 5])
# on Windows. Normalize it here.
if PYTESSERACT_CMD and os.path.isdir(PYTESSERACT_CMD):
    exe_name = "tesseract.exe" if os.name == "nt" else "tesseract"
    candidate = os.path.join(PYTESSERACT_CMD, exe_name)
    PYTESSERACT_CMD = candidate if os.path.exists(candidate) else None

# Any PYTESSERACT_CMD (from env or the folder-fixup above) must point at a
# real, existing file before we trust it — otherwise fall through to
# auto-detection instead of silently misconfiguring pytesseract.
if PYTESSERACT_CMD and not os.path.isfile(PYTESSERACT_CMD):
    PYTESSERACT_CMD = None

if not PYTESSERACT_CMD and os.name == "nt":
    default_windows_path = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
    if os.path.exists(default_windows_path):
        PYTESSERACT_CMD = default_windows_path

if not PYTESSERACT_CMD:
    detected_path = shutil.which("tesseract")
    if detected_path:
        PYTESSERACT_CMD = detected_path

if PYTESSERACT_CMD:
    pytesseract.pytesseract.tesseract_cmd = PYTESSERACT_CMD
    print(f"✅ Tesseract found at: {PYTESSERACT_CMD}")
else:
    print("⚠ Tesseract not installed or PYTESSERACT_CMD is invalid — OCR using pytesseract disabled")

# PWA Settings
PWA_APP_NAME = 'ASK_ME'
PWA_APP_DESCRIPTION = 'AI-powered document assistant'
PWA_APP_THEME_COLOR = '#4f46e5'
PWA_APP_BACKGROUND_COLOR = '#f8fafc'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'portrait'

# Offline mode support
OFFLINE_MODE_ENABLED = True
OFFLINE_STORAGE_TYPE = 'indexeddb'

# --------------------
# CELERY CONFIGURATION (TEMPORARILY DISABLED)
# --------------------
# Celery and Redis are temporarily disabled
# Uncomment when Redis is available
# CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_ACCEPT_CONTENT = ["application/json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_TIMEZONE = TIME_ZONE
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60

GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

