"""
Django settings for ask_me project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

import os
from pathlib import Path
from decouple import config
from dotenv import load_dotenv
import pytesseract
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --------------------
# FILE UPLOAD LIMITS
# --------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# --------------------
# BASE DIR
# --------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------
# SECURITY
# --------------------
SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# --------------------
# CSRF TRUSTED ORIGIN
# --------------------
CSRF_TRUSTED_ORIGINS = [
    "https://ask-me-smart-document-assistant.onrender.com",
]

# --------------------
# INSTALLED APPS
# --------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Local apps
    "account",
    "ask_me",
    "core.apps.CoreConfig",
]

# --------------------
# MIDDLEWARE
# --------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # for static files on Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "account.middleware.active_user_middleware.ActiveUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ask_me.urls"

# --------------------
# TEMPLATES
# --------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # global templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ask_me.wsgi.application"

# --------------------
# DATABASE
# --------------------
DATABASES = {
    "default": dj_database_url.parse(
        config("DATABASE_URL"), conn_max_age=600, ssl_require=True
    )
}

# --------------------
# PASSWORD VALIDATION
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------
# GLOBAL SETTINGS
# --------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = config("TIME_ZONE", default="Asia/Kolkata")
USE_I18N = True
USE_TZ = True

# --------------------
# STATIC FILES
# --------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise file compression (Django 5 compatible)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# --------------------
# MEDIA FILES
# --------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# --------------------
# AUTH / SITE
# --------------------
SITE_ID = 1
LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "core:index"

# --------------------
# DEFAULT PK FIELD
# --------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------
# LOGGING
# --------------------
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "ask_me.log"),
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "ask_me": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# --------------------
# OCR SETTINGS
# --------------------
import shutil
import pytesseract

# 1️⃣ Try env variable first
PYTESSERACT_CMD = os.getenv("PYTESSERACT_CMD")

# 2️⃣ Windows default install path
if not PYTESSERACT_CMD and os.name == "nt":
    default_windows_path = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
    if os.path.exists(default_windows_path):
        PYTESSERACT_CMD = default_windows_path

# 3️⃣ Linux auto detect (Render)
if not PYTESSERACT_CMD:
    detected_path = shutil.which("tesseract")
    if detected_path:
        PYTESSERACT_CMD = detected_path

# 4️⃣ FINAL CHECK (required by ocr_utils)
if not PYTESSERACT_CMD:
    raise RuntimeError("❌ Tesseract not found. Install it or define PYTESSERACT_CMD")

# 5️⃣ Apply to pytesseract
pytesseract.pytesseract.tesseract_cmd = PYTESSERACT_CMD
