"""
Django settings for ask_me project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

import os
from pathlib import Path
from urllib.parse import urlparse, parse_qsl

from decouple import config
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --------------------
# FILE UPLOAD LIMITS
# --------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# --------------------
# SECURITY
# --------------------
# Default is provided so build-time commands (collectstatic, etc.) don't
# crash when env vars aren't injected yet. Render will supply the real one.
SECRET_KEY = config("SECRET_KEY", default="placeholder-set-secret-key-in-env")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Configurable via env so this isn't pinned to one specific Render app name -
# set CSRF_TRUSTED_ORIGINS="https://your-app.onrender.com,https://yourdomain.com"
# (comma-separated, each including the scheme) once you know the real deployed URL(s).
_csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "https://ask-me-smart-document-assistant.onrender.com")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted.split(",") if origin.strip()]

# HTTPS/cookie hardening - only enforced in production (DEBUG=False).
# Left off locally so `runserver` over plain http:// keeps working.
if not DEBUG:
    # Render (and most PaaS free tiers) terminate TLS at a reverse proxy and
    # forward to the app over plain HTTP, setting X-Forwarded-Proto to tell
    # you the original scheme. Without this, Django's request.is_secure()
    # is always False behind that proxy, and SECURE_SSL_REDIRECT=True below
    # causes an infinite redirect loop (https -> proxy -> http -> "not
    # secure, redirect to https" -> ...). This line is required for
    # SECURE_SSL_REDIRECT to work at all on Render.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# --------------------
# DATABASE
# --------------------
# Use Postgres when DATABASE_URL is provided (Render, or locally via .env).
# Otherwise fall back to SQLite — this is what lets build-time commands
# like `collectstatic` run inside Docker before Render injects env vars.
# DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip().strip("'\"")

if DATABASE_URL:
    tmpPostgres = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": tmpPostgres.path.replace("/", ""),
            "USER": tmpPostgres.username,
            "PASSWORD": tmpPostgres.password,
            "HOST": tmpPostgres.hostname,
            "PORT": tmpPostgres.port or 5432,
            "OPTIONS": dict(parse_qsl(tmpPostgres.query)),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# --------------------
# EMAIL
# --------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# --------------------
# INSTALLED APPS
# --------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Local apps
    "account",
    "ask_me",
    "core.apps.CoreConfig",
]

# --------------------
# MIDDLEWARE
# --------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ask_me.urls"

# --------------------
# TEMPLATES
# --------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ask_me.wsgi.application"

# --------------------
# PASSWORD VALIDATION
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------
# GLOBAL SETTINGS
# --------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = config("TIME_ZONE", default="Asia/Kolkata")
USE_I18N = True
USE_TZ = True

# --------------------
# STATIC FILES
# --------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --------------------
# MEDIA FILES
# --------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# --------------------
# AUTH / SITE
# --------------------
SITE_ID = 1
LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "core:index"

# --------------------
# DEFAULT PK FIELD
# --------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------
# LOGGING
# --------------------
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "ask_me.log"),
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "ask_me": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# --------------------
# TEXT EXTRACTION (AI-based, free tier)
# --------------------
# Tesseract/OpenCV OCR is disabled for now (removed the pytesseract system
# dependency entirely — no more Tesseract binary needed on the server).
# Document text extraction now goes through core/ai_extract.py, which uses
# Google Gemini's free API tier (GEMINI_API_KEY below) instead. This makes
# deploys simpler (no system OCR binary to install) and generally reads
# messier photos/scans better than Tesseract did.
USE_AI_EXTRACTION = True

# PWA Settings
PWA_APP_NAME = 'ASK_ME'
PWA_APP_DESCRIPTION = 'AI-powered document assistant'
PWA_APP_THEME_COLOR = '#4f46e5'
PWA_APP_BACKGROUND_COLOR = '#f8fafc'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'portrait'

# Offline mode support
OFFLINE_MODE_ENABLED = True
OFFLINE_STORAGE_TYPE = 'indexeddb'

# --------------------
# CELERY CONFIGURATION (TEMPORARILY DISABLED)
# --------------------
# CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_ACCEPT_CONTENT = ["application/json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_TIMEZONE = TIME_ZONE
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60

# --------------------
# THIRD-PARTY / AI SERVICES
# --------------------
GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

# --------------------
# AT-REST ENCRYPTION (core/crypto_fields.py)
# --------------------
# Encrypts Document.extracted_text / extracted_data / user_edited_data /
# ai_extracted_json (Aadhaar/PAN/DOB/address/etc.) before they hit the
# database. Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Leave blank in local dev if you don't need it yet - fields fall back to
# storing plain JSON/text unencrypted, and existing plaintext rows are still
# readable if you turn this on later. Losing this key makes previously
# encrypted documents permanently unreadable - store it like a password
# (e.g. your host's secret manager), never in source control.
DOCUMENT_ENCRYPTION_KEY = config("DOCUMENT_ENCRYPTION_KEY", default="")
